runtime: python39
entrypoint: gunicorn -b :$PORT demo.wsgi
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65


env_variables:
  MONGODB_URI: "mongodb+srv://krishteccbe:<KRISHtec@5747>@ktcluster.cor4zzm.mongodb.net/?retryWrites=true&w=majority"
  API_KEY: fGkzsgelPFFywCHUAmVJM5rVWMGThu0vFt7cApbEDP7b7ARhXBvoAzmcdCVohSWY
