# Generated by Django 4.2.4 on 2023-08-22 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('admin_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_emailId', models.CharField(max_length=400, unique=True)),
                ('admin_password', models.CharField(max_length=100)),
                ('admin_contact_number', models.IntegerField(unique=True)),
                ('Register_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='device_table',
            fields=[
                ('device_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_table_names_gauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_table_names_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_table_names_of_gauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_table_names_switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_table_names_toggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_register_details',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField()),
                ('emailId', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('Register_date', models.DateField(auto_now=True)),
                ('street_name', models.CharField(default='', max_length=400)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=100)),
                ('Institute_name', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='toggle_switch',
            fields=[
                ('toggle_switch_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('on_val', models.IntegerField()),
                ('off_val', models.IntegerField()),
                ('mqtt_topic', models.TextField()),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Iot_platform_app.device_table')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('mqtt_topic', models.TextField()),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Iot_platform_app.device_table')),
            ],
        ),
        migrations.CreateModel(
            name='Gauge_table',
            fields=[
                ('gauge_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('min_val', models.IntegerField()),
                ('max_val', models.IntegerField()),
                ('mqtt_topic', models.TextField()),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Iot_platform_app.device_table')),
            ],
        ),
        migrations.CreateModel(
            name='electric_switch',
            fields=[
                ('electric_switch_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('on_val', models.IntegerField()),
                ('off_val', models.IntegerField()),
                ('mqtt_topic', models.TextField()),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Iot_platform_app.device_table')),
            ],
        ),
        migrations.AddField(
            model_name='device_table',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Iot_platform_app.user_register_details'),
        ),
    ]
