# Generated by Django 4.2.4 on 2023-08-22 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iot_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bddda48d-f63f-4b5f-bacc-c278202b1e00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_field_1', models.DateTimeField(default=datetime.datetime.now)),
                ('common_field_2', models.IntegerField()),
            ],
            options={
                'db_table': 'bddda48d-f63f-4b5f-bacc-c278202b1e00',
            },
        ),
    ]
